"""Train offspring models from generated training data.

Each offspring starts from the BASE checkpoint (not from its parent)
and is fine-tuned exclusively on the training data generated by
its parent. This is the "compartment" — each offspring only sees
data from one parent.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

import torch
from torch.utils.data import DataLoader, Dataset

from csr_llm.model import TinyGPT, load_model, save_model
from csr_llm.task import ParsedExample
from csr_llm.tokenizer import encode

logger = logging.getLogger(__name__)


class GeneratedDataset(Dataset):
    """Dataset built from parsed model-generated examples."""

    def __init__(self, examples: list[ParsedExample], tokenizer, max_len: int = 128):
        self.samples = []
        bos = tokenizer.token_to_id("<bos>")
        eos = tokenizer.token_to_id("<eos>")
        pad = tokenizer.token_to_id("<pad>")

        # Pack multiple examples per sequence to match pretraining format.
        # Pretraining uses [bos] + chain_of_examples + [eos] per chunk.
        # Per-example BOS/EOS wrapping taught offspring to emit EOS after
        # every single example, killing generation after ~1 line.
        all_ids = []
        for ex in examples:
            if not ex.is_valid:
                continue
            all_ids.extend(encode(tokenizer, ex.raw + "\n"))

        for start in range(0, len(all_ids) - max_len, max_len):
            chunk = [bos] + all_ids[start : start + max_len - 2] + [eos]
            if len(chunk) < max_len:
                chunk = chunk + [pad] * (max_len - len(chunk))
            self.samples.append(torch.tensor(chunk, dtype=torch.long))

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        s = self.samples[idx]
        return s[:-1], s[1:]


def train_offspring(
    base_checkpoint: str | Path,
    parsed_examples: list[ParsedExample],
    tokenizer,
    cfg: dict,
    device: str = "cuda",
    save_path: Optional[str | Path] = None,
) -> TinyGPT:
    """Train one offspring from base checkpoint using generated data.

    Args:
        base_checkpoint: Path to the base model weights
        parsed_examples: Training data generated by the parent
        tokenizer: The tokenizer
        cfg: Full experiment config
        device: cuda/cpu
        save_path: Optional path to save offspring weights

    Returns:
        Trained offspring model
    """
    ocfg = cfg["offspring"]

    # Load base checkpoint (NOT the parent — this is key)
    model = load_model(base_checkpoint, cfg).to(device)

    # Build dataset from generated examples
    dataset = GeneratedDataset(parsed_examples, tokenizer, max_len=cfg["model"]["max_seq_len"])

    if len(dataset) == 0:
        logger.warning("No valid training examples. Returning None.")
        return None

    loader = DataLoader(
        dataset,
        batch_size=min(ocfg["batch_size"], len(dataset)),
        shuffle=True,
        drop_last=False,
    )

    optimizer = torch.optim.AdamW(model.parameters(), lr=ocfg["learning_rate"], weight_decay=ocfg["weight_decay"])

    model.train()
    step = 0

    while step < ocfg["n_steps"]:
        for input_ids, targets in loader:
            if step >= ocfg["n_steps"]:
                break

            input_ids = input_ids.to(device)
            targets = targets.to(device)

            _, loss = model(input_ids, targets)

            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()

            step += 1

    if save_path:
        save_model(model, save_path)

    return model
